export const cloudinary = "https://res.cloudinary.com/dsbkkhpdq/image/upload";

export const assets = {
  logo: "/techy-bd-logo.png",
  heroCheckout: `${cloudinary}/v1786481754/hero/checkout/le3a1nkw3qqyqpgf940t.webp`,
  heroProductOne: `${cloudinary}/v1786481197/hero/products/edspmcegeuc22hexa8ky.webp`,
  heroProductTwo: `${cloudinary}/v1786481246/hero/products/zthaxnru0gagcjvwzo5c.webp`,
  heroProductThree: `${cloudinary}/v1786481251/hero/products/nz6dmd7wofgiff7crtr1.webp`,
  hosting: `${cloudinary}/v1780859871/free-hosting/jhfbqouqmxkpqywalau7.webp`,
  offerOne: `${cloudinary}/v1777832292/hot-offers/qveujpsesdafzchxsyzx.png`,
  offerTwo: `${cloudinary}/v1777832302/hot-offers/fcpxobpwtat68sd5et5m.png`,
  ecommerceService: `${cloudinary}/v1783785294/services/voqdj9mzwr7kizjhisie.png`,
  landingService: `${cloudinary}/v1783785305/services/jkxhphihblgoydcfacrm.png`,
  pixelService: `${cloudinary}/v1780858740/services/enx5dk0gehsip9vczwca.webp`,
  trackingService: `${cloudinary}/v1780858931/services/ijn39i9ryvyxiso4yqgx.webp`,
  maintenanceService: `${cloudinary}/v1781338799/services/e8teffl3cejksrguce6m.webp`,
};

// Offline fallback and initial CMS seed.
export const siteSettings = {
  brand: {
    name: "Techy BD",
    logoUrl: "/techy-bd-logo.png",
    tagline: "Premium Websites for Growing Bangladeshi Businesses",
    description: "We design and build high-quality eCommerce, business websites, landing pages and digital experiences for growing brands in Bangladesh.",
    footerCopy: "We design and build premium websites and digital experiences for growing businesses in Bangladesh.",
    copyright: "© 2026 Techy BD. All rights reserved.",
  },
  nav: [
    { label: "Home", path: "/" },
    { label: "Project", path: "/work" },
    { label: "Services", path: "/services" },
    // { label: "About", path: "/about" },
    { label: "Contact", path: "/contact" },
  ],
  contact: {
    email: "info@techybd.com",
    phone: "01581503522",
    whatsapp: "01581503522",
    whatsappUrl: "https://wa.me/8801581503522?text=Hi%20Techy%20BD%2C%20I%27d%20like%20to%20discuss%20a%20website%20project.",
    availability: "All Days",
    address: "196/D, Amtola, Khilkhet Namapara, Dhaka-1229",
    socials: {
      facebook: "https://www.facebook.com/share/18Jr82howW/",
      instagram: "https://www.instagram.com/iambadolskofficial",
      linkedin: "https://www.linkedin.com/in/badol-sk",
    },
  },
  seo: {
    title: "Techy BD — Premium Websites for Bangladeshi Businesses",
    description: "Techy BD designs and builds premium eCommerce, business websites, landing pages and digital experiences for growing businesses in Bangladesh.",
  },
  assets: { ...assets },
  home: {
    hero: {
      trustLabel: "● Helping Bangladeshi businesses grow online",
      overline: "Websites that make",
      title: "Bangladeshi businesses look premium.",
      copy: "We design and build high-quality eCommerce, business websites, landing pages and digital experiences for growing brands in Bangladesh.",
      primaryCtaLabel: "View Our Work →",
      secondaryCtaLabel: "Start a Project →",
      supportingLine: "eCommerce • Business Websites • Landing Pages",
    },
    trust: {
      heading: "Trusted by growing businesses",
      statement: "Websites designed for ambitious Bangladeshi businesses.",
      pillars: [
        { title: "Mobile-First", copy: "Optimized for seamless phone browsing and fast 4G connections." },
        { title: "Conversion-Focused", copy: "Structured layouts and clear calls to action to drive real sales." },
        { title: "Fast & Responsive", copy: "Ultra-clean code ensuring instant page load times." },
        { title: "Bangladesh-Focused", copy: "Native bKash, Nagad, Cash on Delivery, and WhatsApp integration." },
      ],
      rails: ["bKash", "Nagad", "Rocket", "Cash on Delivery", "Pathao", "Steadfast", "Shopify", "WooCommerce", "Next.js"],
    },
    work: {
      eyebrow: "Selected Work",
      title: "Selected Work",
      copy: "A selection of websites we've designed and built for businesses and brands in Bangladesh.",
      allLinkLabel: "View All Projects →",
      featuredLimit: 6,
      pageEyebrow: "Portfolio",
      pageTitle: "Digital experiences made to stand out.",
      pageCopy: "Explore our complete showcase of eCommerce stores, business sites, landing pages, and web apps.",
    },
    services: {
      eyebrow: "What we build",
      title: "What we build",
      copy: "From business websites to high-converting landing pages, we build digital experiences designed around your business goals.",
      pageEyebrow: "Services",
      pageTitle: "Services designed to grow your business online.",
      pageCopy: "Clean code, mobile-first design, and seamless local payment workflows.",
    },
    why: {
      eyebrow: "Why Techy BD",
      title: "Why Techy BD",
      copy: "Five clear standards that set our work apart.",
      items: [
        { icon: "sparkles", title: "Premium Design", copy: "Clean, modern and professional interfaces that elevate your brand identity." },
        { icon: "mobile", title: "Mobile First", copy: "Designed to work properly across phones, tablets and desktops." },
        { icon: "trending", title: "Conversion Focused", copy: "Layouts and content structured around clear business goals and orders." },
        { icon: "zap", title: "Fast & Responsive", copy: "Optimized for real-world browsing speeds on local networks." },
        { icon: "shopping", title: "Built for Bangladesh", copy: "Designed with Bangladeshi businesses and customers in mind." },
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "How we work",
      copy: "A simple, transparent four-step process for launch readiness.",
      items: [
        ["01", "Discover", "We understand your business, audience, products, and growth goals."],
        ["02", "Plan", "We define the layout structure, conversion path, and user journey."],
        ["03", "Design & Build", "We design and develop the website with responsive behavior."],
        ["04", "Launch", "We test on real devices, polish details, and prepare the site for launch."],
      ],
    },
    testimonials: {
      eyebrow: "Testimonials",
      title: "What our clients say",
      copy: "Built for businesses that want to look better online.",
    },
    finalCta: {
      eyebrow: "Have a business idea?",
      title: "Let's turn it into a website that works for your business.",
      copy: "Tell us what you're building. We'll help you choose the right website structure and next steps.",
      primaryLabel: "Start a Project →",
      secondaryLabel: "Chat on WhatsApp →",
    },
  },
};

export const projects = [
  {
    slug: "purebangla",
    title: "PureBangla — Organic eCommerce",
    category: "eCommerce",
    status: "LIVE",
    featured: true,
    image: `${cloudinary}/v1785708445/projects/mrt8uk4pf7k30tako4rx.png`,
    href: "https://organik.skitsolutionsbd.com",
    description: "A mobile-first eCommerce experience designed for a modern organic products brand in Bangladesh.",
    overview: "PureBangla offers natural and organic food products across Bangladesh. The storefront was engineered to simplify product discovery, highlight product purity, and provide a 1-click checkout flow.",
    challenge: "Bangladeshi buyers needed trust signals for organic authenticity and an effortless checkout experience without forcing account creation.",
    approach: "We designed a warm, earth-toned UI with high-contrast callouts for organic certifications, instant mobile cart drawer, and prominent bKash/COD payment options.",
    keyFeatures: [
      "Mobile-first responsive storefront",
      "Instant search & category filter pills",
      "Direct Cash-on-Delivery & bKash ordering flow",
      "Fast page load optimization under 1.5s",
    ],
    designDirection: "Soft organic greens, clean cream backgrounds, legible typography, and spacious product cards.",
    result: "Better product presentation, improved mobile experience, clearer navigation, and stronger visual hierarchy.",
  },
  {
    slug: "sk-streetwear",
    title: "SK Streetwear — Fashion eCommerce",
    category: "eCommerce",
    status: "LIVE",
    featured: true,
    image: `${cloudinary}/v1785865742/projects/cea4c7l1uu2rmm0lshc4.webp`,
    href: "https://skworld.skitsolutionsbd.com/",
    description: "A high-performance, full-stack eCommerce experience for a modern Bangladeshi streetwear clothing brand.",
    overview: "SK Streetwear required an energetic, modern fashion storefront to showcase limited-edition apparel drops to young urban buyers in Dhaka.",
    challenge: "Traditional eCommerce templates felt generic and cluttered on mobile devices, slowing down campaign conversions.",
    approach: "We built a high-impact dark mode layout featuring bold typography, dynamic size selectors, and streamlined checkout.",
    keyFeatures: [
      "Dynamic apparel size selector & stock indicators",
      "High-contrast product gallery carousel",
      "Integrated delivery location auto-calculator",
      "Seamless mobile ordering",
    ],
    designDirection: "Deep navy and charcoal canvas with vibrant contrast accents and strong headline typography.",
    result: "Significantly enhanced visual credibility, smoother mobile buying flow, and refined brand presentation.",
  },
  {
    slug: "novatek",
    title: "Novatek — Digital Marketplace",
    category: "eCommerce",
    status: "LIVE",
    featured: true,
    image: `${cloudinary}/v1785708622/projects/ubohkohceprtkaa9xmhz.png`,
    href: "https://novatekdigital.shop",
    description: "A premium digital marketplace for software subscriptions, AI tools, and creative assets.",
    overview: "Novatek needed a sleek, trustworthy platform for delivering digital license keys and digital services with instant checkout.",
    challenge: "Digital service websites in Bangladesh often struggle with buyer trust and customer confusion around fulfillment.",
    approach: "We built a structured grid showcasing verified badges, instant instant delivery promises, and transparent pricing cards.",
    keyFeatures: [
      "Categorized digital product inventory",
      "Instant checkout integration",
      "Verified service badges and buyer FAQs",
      "Live support integration",
    ],
    designDirection: "Modern tech aesthetic with deep indigo tones, glowing status pills, and crisp card borders.",
    result: "Clearer navigation, stronger buyer trust, and streamlined checkout UX.",
  },
  {
    slug: "starbucks-drinks",
    title: "Starbucks Drinks",
    category: "Restaurant",
    status: "LIVE",
    featured: true,
    image: `${cloudinary}/v1786480906/projects/pde4eg8nd6u0nhaiuekb.webp`,
    href: "https://starbucks.skitsolutionsbd.com",
    description: "A premium promotional website for beverage menus, seasonal campaigns, and cafe branch locator.",
    overview: "Designed as an immersive promotional digital menu showcasing signature drinks, seasonal iced matchas, and branch locations.",
    challenge: "Converting passive social media browsers into active store visitors through compelling visual menus.",
    approach: "Emphasized high-resolution product photography, crisp typography, and interactive category toggles.",
    keyFeatures: [
      "High-res visual menu layout",
      "Seasonal offer hero banner",
      "Mobile-optimized nutritional & pricing cards",
      "Store locator integration",
    ],
    designDirection: "Rich deep green and cream aesthetic, luxury editorial typography, and appetizing macro photography.",
    result: "Stronger visual engagement, intuitive menu navigation, and clean mobile presentation.",
  },
  {
    slug: "digital-toolbox",
    title: "Digital Toolbox — Web Utilities",
    category: "Service",
    status: "LIVE",
    featured: true,
    image: `${cloudinary}/v1786937174/projects/qwddb5laazhbdcuokwfm.webp`,
    href: "https://tools.skitsolutionsbd.com/",
    description: "A fast, privacy-focused collection of free digital productivity tools for Bangladeshi creators.",
    overview: "Digital Toolbox packs essential utility tools—including image converters, text counters, and unit calculators—into a lightning-fast interface.",
    challenge: "Creating a tool suite that loads instantly without intrusive popups or layout shifts.",
    approach: "Focused on zero-latency client-side calculations, clean dark UI, and intuitive tool search.",
    keyFeatures: [
      "Instant client-side web utility suite",
      "Zero-ad, distraction-free interface",
      "Dark mode utility workspace",
      "Mobile touch-friendly sliders and inputs",
    ],
    designDirection: "Clean developer aesthetic with high contrast, monochrome accents, and pill-shaped navigation.",
    result: "Ultra-fast utility performance, clean mobile accessibility, and clear tool navigation.",
  },
  {
    slug: "vibe-coding",
    title: "Vibe Coding — Bangla Course Launch",
    category: "Courses",
    status: "LIVE",
    featured: true,
    image: `${cloudinary}/v1783887042/projects/rkwayh34v2jqkcxp6uzp.webp`,
    href: "https://vibe.skitsolutionsbd.com/",
    description: "A conversion-led Bangla course landing page for practical AI-assisted web design training.",
    overview: "A high-converting landing page designed to educate student creators and launch an online masterclass in modern web development.",
    challenge: "Communicating complex course modules clearly while motivating enrollments through social proof.",
    approach: "Structured video breakdown, transparent module accordion, student FAQs, and sticky enrollment CTA.",
    keyFeatures: [
      "Bangla curriculum accordion breakdown",
      "Direct bKash enrollment integration",
      "Embedded video walkthroughs",
      "Instructor trust section",
    ],
    designDirection: "Electric blue contrast accents, readable Bangla typography, and prominent action buttons.",
    result: "Higher landing page clarity, direct enrollment flow, and improved mobile conversion rates.",
  },
  {
    slug: "trikonn",
    title: "Trikonn — Men's Clothing Store",
    category: "eCommerce",
    status: "LIVE",
    featured: false,
    image: `${cloudinary}/v1785446117/projects/t7jztyg6levctmzwailn.webp`,
    href: "https://trikon-clothing.pages.dev/",
    description: "Fully dynamic men's clothing eCommerce with responsive storefront, admin panel and COD checkout.",
    overview: "Trikonn provides everyday minimalist clothing for men with automated inventory and admin management.",
    challenge: "Managing frequent inventory updates while preserving an uncluttered storefront experience.",
    approach: "Designed a clean product grid with fast filter tags and seamless order submission.",
    keyFeatures: ["Responsive product showcase", "Admin sync capability", "COD & bKash checkout", "Fast image optimization"],
    designDirection: "Minimalist fashion aesthetic with neutral greys and crisp product framing.",
    result: "Clearer product hierarchy and smooth checkout experience.",
  },
  {
    slug: "mango-tv",
    title: "Mango TV — Display Solutions",
    category: "Service",
    status: "LIVE",
    featured: false,
    image: `${cloudinary}/v1787162681/projects/ryncpfowqjz5hfnkkjvo.webp`,
    href: "https://mango-tv-4o4.pages.dev/",
    description: "Interactive display product pages designed for education and corporate presentation spaces.",
    overview: "Showcase website for smart interactive displays, classroom technology, and corporate presentation boards.",
    challenge: "Explaining technical hardware specs to non-technical institutional buyers.",
    approach: "Feature-comparison tables, visual callouts, and direct inquiry form triggers.",
    keyFeatures: ["Hardware specification matrices", "Use-case gallery", "Direct RFQ inquiry form", "Video demonstrations"],
    designDirection: "Professional corporate navy with clean technology highlights.",
    result: "Improved product specification readability and lead generation.",
  },
  {
    slug: "matir-saj",
    title: "Matir Saj — Restaurant & Menu",
    category: "Restaurant",
    status: "LIVE",
    featured: false,
    image: `${cloudinary}/v1777831875/projects/behytx4wpalli41zl3o1.webp`,
    href: "https://www.matirsaj.shop/",
    description: "A warm restaurant site for showcasing authentic local menu items, offers, and customer trust.",
    overview: "Authentic traditional Bangladeshi dining experience website with digital menu and table reservation details.",
    challenge: "Bringing traditional cultural warmth to a modern digital browser interface.",
    approach: "Warm color tones, authentic food imagery, and quick phone/WhatsApp ordering links.",
    keyFeatures: ["Digital food menu", "Offer announcements", "Location & hours map", "WhatsApp ordering"],
    designDirection: "Earthy terracotta tones, warm typography, and inviting food cards.",
    result: "Enhanced customer trust and clear digital menu presentation.",
  },
  {
    slug: "scent-luxe",
    title: "Scent Luxe — Fragrance Landing Page",
    category: "Landing Pages",
    status: "CONCEPT",
    featured: false,
    image: `${cloudinary}/v1782544821/projects/tggakwgr8wfcsdz1vwqg.webp`,
    href: "https://supabound-flow.lovable.app",
    description: "Luxury fragrance landing page with immersive visuals and a high-converting shopping experience.",
    overview: "A single-product campaign page focused on premium perfume presentation and storytelling.",
    challenge: "Creating an aura of luxury for online perfume purchases where scent cannot be physically sampled.",
    approach: "Focus on olfactory note visual breakdowns, scent longevity badges, and customer reviews.",
    keyFeatures: ["Single-product focus flow", "Fragrance note pyramid breakdown", "Express checkout", "Customer ratings"],
    designDirection: "Elegant dark luxury tone with subtle gold accents.",
    result: "High visual impact and focused conversion path.",
  },
  {
    slug: "aurelia-mode",
    title: "Aurelia Mode — Luxury Fashion",
    category: "eCommerce",
    status: "CONCEPT",
    featured: false,
    image: `${cloudinary}/v1781781291/projects/xwoqzw4ydckvnjmp7mib.webp`,
    href: "https://auerella-mood.lovable.app",
    description: "Clean luxury fashion eCommerce with elegant typography and soft neutral product presentation.",
    overview: "A refined boutique clothing storefront concept designed for luxury apparel lines.",
    challenge: "Achieving an editorial magazine feel while maintaining high mobile purchasing speeds.",
    approach: "Spacious layout, subtle image hover zooms, and elegant serif display titles.",
    keyFeatures: ["Editorial lookbook layout", "Filter by collection", "Soft neutral aesthetics", "Seamless cart"],
    designDirection: "Soft cream, charcoal, and warm taupe palette with serif headlines.",
    result: "Premium brand feel and clean mobile presentation.",
  },
  {
    slug: "nexora",
    title: "Nexora — Tech Store",
    category: "eCommerce",
    status: "CONCEPT",
    featured: false,
    image: `${cloudinary}/v1778758122/projects/c2zjl0mk5jyo7atprdex.webp`,
    href: "https://aloof-nexora-tech-flow.base44.app",
    description: "A modern gadgets store with secure payment, warranty callouts, and nationwide delivery details.",
    overview: "A futuristic gadget and consumer electronics storefront built for fast catalog browsing.",
    challenge: "Highlighting warranty and authenticity details clearly on every product card.",
    approach: "Structured specification badges, quick-view product modal, and explicit delivery timelines.",
    keyFeatures: ["Warranty badge callouts", "Tech spec tabs", "bKash & COD ready", "Fast product filtering"],
    designDirection: "Cyber navy background with electric cyan accents.",
    result: "Stronger trust signals and intuitive catalog browsing.",
  },
  {
    slug: "glowr-skincare",
    title: "Glowr — Skincare Store",
    category: "Beauty & Skincare",
    status: "CONCEPT",
    featured: false,
    image: `${cloudinary}/v1777831903/projects/mdpm8y8yihugeh07kmvy.webp`,
    href: "https://glowr-pure-bd.base44.app",
    description: "Premium skincare storefront concept with elegant product presentation and beauty-led storytelling.",
    overview: "A beauty-focused storefront designed to showcase dermatologically tested skincare products.",
    challenge: "Building customer confidence in skincare ingredients and usage routines.",
    approach: "Ingredient breakdown pills, step-by-step skincare routine guides, and verified reviews.",
    keyFeatures: ["Skin-type product filter", "Ingredient safety badges", "Routine builder guide", "Mobile checkout"],
    designDirection: "Clean pastel hues, soft white surfaces, and refined typography.",
    result: "Improved mobile experience and clearer product transparency.",
  },
];

export const services = [
  {
    slug: "ecommerce-websites",
    title: "01 — eCommerce Websites",
    price: "From 12,499 BDT",
    image: assets.ecommerceService,
    icon: "shopping-bag",
    description: "Modern online stores designed for product discovery, trust and conversion. Mobile-first with bKash, Nagad, and Cash on Delivery baked in.",
  },
  {
    slug: "business-websites",
    title: "02 — Business Websites",
    price: "From 9,999 BDT",
    image: assets.landingService,
    icon: "zap",
    description: "Professional websites for service-based businesses and growing companies that want to build authority and capture qualified leads.",
  },
  {
    slug: "landing-pages",
    title: "03 — Landing Pages",
    price: "From 4,999 BDT",
    image: assets.pixelService,
    icon: "sparkles",
    description: "Focused landing pages designed for campaigns, products and lead generation. Built specifically to maximize Facebook and Google ad conversions.",
  },
  {
    slug: "course-ebook-websites",
    title: "04 — Course & eBook Websites",
    price: "From 6,999 BDT",
    image: assets.trackingService,
    icon: "activity",
    description: "Sales-focused digital product experiences for creators and educators. Clean layout with direct curriculum preview and instant access.",
  },
  {
    slug: "website-automation",
    title: "05 — Website Automation",
    price: "From 2,999 BDT",
    image: assets.maintenanceService,
    icon: "shield-check",
    description: "Lead forms, Meta Pixel & Conversion API setup, messaging integrations, workflows and business automation where needed.",
  },
];

export const offers = [
  {
    slug: "new-hot-offer-for-first-7-clients",
    title: "New Launch Offer — First 7 Clients",
    price: "3,999 BDT",
    was: "5,999 BDT",
    image: assets.offerOne,
    accent: "electric",
    body: "Dynamic CMS admin dashboard, free cloud hosting, .XYZ domain, mobile responsive design and fast conversion-focused layout.",
  },
  {
    slug: "ecommerce-website-design",
    title: "Full eCommerce Package",
    price: "৳ 12,499",
    was: "৳ 24,999",
    image: assets.offerTwo,
    accent: "accent",
    body: "A premium Bangladeshi eCommerce site with product showcase, bKash/Nagad/COD checkout, admin control panel and launch support.",
  },
];

export const testimonials = [
  {
    name: "রুমানা আক্তার",
    role: "Founder",
    brand: "Skincare ব্র্যান্ড",
    quote: "আমাদের স্টোরটা এখন template না, একদম আমাদের ব্র্যান্ডের মতো লাগে। মোবাইল চেকআউট নিয়ে কাস্টমাররা সবচেয়ে বেশি কথা বলে।",
    avatar: `${cloudinary}/v1777832158/testimonials/avatars/qk5clpl9bczfebu7jeu7.png`,
  },
  {
    name: "সায়েদ হোসেন",
    role: "Senior Product Designer",
    brand: "Maatir Saaj",
    quote: "ক্লিন, প্রিমিয়াম, আর স্পষ্টভাবে বাংলাদেশি বায়ারদের জন্য বানানো। বেশিরভাগ BD eCommerce কাজ এই লেভেলে পৌঁছায় না।",
    avatar: `${cloudinary}/v1777832227/testimonials/avatars/okuf0vqnqhzqd9u6yii1.png`,
  },
  {
    name: "সাবরিনা ইসলাম",
    role: "Founder",
    brand: "Noor Skincare",
    quote: "Bangla typography আর design balance — একদম professional লাগে। আমাদের brand identity পুরোপুরি ফুটে উঠেছে।",
    avatar: `${cloudinary}/v1777832233/testimonials/avatars/qlkqmay0m2rorb7eriym.png`,
  },
  {
    name: "ইমরান কবির",
    role: "eCommerce Manager",
    brand: "Skincare ব্র্যান্ড",
    quote: "Admin panel এত সহজ যে আমার team নিজেই product update করতে পারে। কোনো dev এর জন্য wait করতে হয় না।",
    avatar: `${cloudinary}/v1777832240/testimonials/avatars/lre2lcwt5o8oyefbjiyi.png`,
  },
];

export const faqItems = [
  ["পেমেন্ট কীভাবে নেবেন — অ্যাডভান্স কত?", "প্রজেক্টের scope ঠিক হওয়ার পর কাজ শুরু করার জন্য advance নেওয়া হয়। বাকি অংশ milestone অনুযায়ী পরিষ্কারভাবে জানানো থাকে।"],
  ["লঞ্চের পর কোনো সাপোর্ট পাব?", "হ্যাঁ। লঞ্চের পর handover support এবং প্রয়োজন অনুযায়ী monthly maintenance support রাখা যায়।"],
  ["bKash, Nagad, COD সেটআপ সব দিয়ে দেবেন?", "আপনার ব্যবসার flow অনুযায়ী bKash, Nagad, COD এবং WhatsApp ordering option সাজিয়ে দেওয়া হয়।"],
  ["আমি নিজে এডিট করতে পারব?", "হ্যাঁ, প্রয়োজন অনুযায়ী সহজ admin workflow এবং handover guide দেওয়া হয়।"],
  ["প্রজেক্ট দেরি হলে কী হবে?", "শুরুর আগে একটি পরিষ্কার timeline দেওয়া হয়। কোনো পরিবর্তন হলে আগে থেকেই জানিয়ে দেওয়া হয়।"],
];

export const customers = [
  {
    id: "cust-1",
    name: "MD Omar Faruk",
    emailOrPhone: "01581503522",
    status: "Active",
    totalOrders: "2 Orders",
    totalSpent: "৳ 15,498",
    notes: "Purchased PureBangla Organic eCommerce Site & Meta Pixel Setup.",
  },
  {
    id: "cust-2",
    name: "রুমানা আক্তার",
    emailOrPhone: "01712345678",
    status: "VIP",
    totalOrders: "3 Orders",
    totalSpent: "৳ 28,997",
    notes: "Noor Skincare brand owner. Requested monthly maintenance support.",
  },
  {
    id: "cust-3",
    name: "সায়েদ হোসেন",
    emailOrPhone: "sayed@maatirsaaj.com",
    status: "Active",
    totalOrders: "1 Order",
    totalSpent: "৳ 12,499",
    notes: "Maatir Saaj Product Store.",
  },
];
